server:
  port: 1201

spring:
  datasource:
    username: root
    password: sherlock
    url: jdbc:mysql://120.76.60.77:2061/gmall_oms?characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    ###################以下为druid增加的配置###########################
    # 合并多个DruidDataSource的监控数据
    #spring.datasource.useGlobalDataSourceStat=true
    type: com.alibaba.druid.pool.DruidDataSource

    druid:
      # 配置监控统计拦截的servlet
      stat-view-servlet:
        login-username: admin
        login-password: admin
        url-pattern: /druid/*
        enabled: true # 是否启用StatViewServlet（监控页面）默认值为true（考虑到安全问题默认并未启动，如需启用建议设置密码或白名单以保障安全）
        # allow: 允许访问的白名单
        # deny:  拒绝访问的黑名单

      # 配置监控统计拦截的filters
      web-stat-filter:
        url-pattern: /*
        exclusions: "*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*"

      initialSize: 8 #初始化连接大小
      minIdle: 8  #最小连接池数量
      maxActive: 20 #最大连接池数量
      max-wait: 6000 #获取连接时最大等待时间，单位毫秒
      time-between-connect-error-millis: 28820 #配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      ###[ERROR]-->minEvictableIdleTimeMillis should be greater than 30000###
      minEvictableIdleTimeMillis: 30000  #配置一个连接在池中最小生存的时间，单位是毫秒
      validationQuery: SELECT 1 FROM DUAL  #测试连接
      testWhileIdle: true   #申请连接的时候检测，建议配置为true，不影响性能，并且保证安全性
      testOnBorrow: false #获取连接时执行检测，建议关闭，影响性能
      testOnReturn: false #归还连接时执行检测，建议关闭，影响性能
      poolPreparedStatements: false #是否开启PSCache，PSCache对支持游标的数据库性能提升巨大，oracle建议开启，mysql下建议关闭
      maxPoolPreparedStatementPerConnectionSize: 20 #开启poolPreparedStatements后生效
      filters: stat #配置扩展插件，常用的插件有=>stat:监控统计  log4j:日志  wall:防御sql注入
      connectionProperties: 'druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000' #通过connectProperties属性来打开mergeSql功能;慢SQL记录
      query-timeout: 10000 #查询超时时间
      # default-transaction-isolation: #默认隔离级别

  cloud:
    nacos:
      discovery:
        server-addr: 120.76.60.77:9848
  application:
    name: gmall-order

  rabbitmq:
    host: 192.168.1.4
    port: 5672
    virtual-host: /
    username: guest
    password: guest
    #publisher-confirms: true #开启发送端确认 发送端->rabbitmq服务器
    publisher-confirm-type: correlated  #配合CorrelationData类使用，发送消息时添加消息的唯一ID
    publisher-returns: true #开启发送端确认 rabbitmq服务器(交换机)->queue 没有到达才会触发
    template:
      mandatory: true #只要消息抵达队列，以异步的方式优先回调 returnConfirm 接口
    listener:
      simple:
        acknowledge-mode: manual #手动确认收货(消息被正确消费)
  thymeleaf:
    cache: false
  # redis相关信息配置
  redis:
    host: 120.76.60.77
    password: sherlock
    port: 7379
  session:
    store-type: redis

mybatis-plus:
  # 虽然我不知道为啥在源码和自动提示都是config-location，但是这样就报错，需要修改成config-locations(带s)
  config-locations: classpath:/mapper/**/*.xml
  # 所有的实体主键自增
  global-config:
    db-config:
      id-type: auto
logging:
  level:
    com.sherlock.gmall: debug
    com.alibaba.nacos.client.naming: error

swagger:
  enabled: false

#自定义线程池配置
gmall:
  thread:
    core-pool-size: 10
    maximum-pool-size: 200
    keep-alive-time: 10