server:
  port: 1801

spring:
  cloud:
    nacos:
      discovery:
        server-addr: 120.76.60.77:9848

  application:
    name: gmall-cart
  redis:
    host: 120.76.60.77
    port: 7379
    password: sherlock
    database: 1
  session:
    store-type: redis
  thymeleaf:
    cache: false
logging:
  level:
    com.sherlock.gmall: debug
    com.alibaba.nacos.client.naming: error
swagger:
  enabled: false

#自定义线程池配置
gmall:
  thread:
    core-pool-size: 10
    maximum-pool-size: 200
    keep-alive-time: 10
