spring:
  cloud:
    gateway:
      routes:
        - id: qq_routes
          uri: https://www.qq.com
          predicates:
            - Query=url,qq


        - id: baidu_routes
          uri: https://www.baidu.com
          predicates:
            - Query=url,baidu


        - id: product_route
          uri: lb://gmall-product  #转到哪个服务
          predicates:
            - Path=/api/product/**  #拦截path包含/api的请求
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}  #请求地址经过网关进行转换

        - id: member_route
          uri: lb://gmall-member  #转到哪个服务
          predicates:
            - Path=/api/member/**  #拦截path包含/api的请求
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}  #请求地址经过网关进行转换

        - id: third_party_route
          uri: lb://gmall-third-party  #转到哪个服务
          predicates:
            - Path=/api/thirdparty/**  #拦截path包含/api的请求
          filters:
            - RewritePath=/api/thirdparty/(?<segment>.*),/$\{segment}  #请求地址经过网关进行转换

        - id: admin_route
          uri: lb://renren-fast #转到哪个服务
          predicates:
            - Path=/api/**  #拦截path包含/api的请求
          filters:
            - RewritePath=/api/(?<segment>.*),/renren-fast/$\{segment}  #请求地址经过网关进行转换